version: '3'

services:
  irida-db:
    build: db
    image: dfornika/irida-db
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    ports:
      - "3306"
  irida:
    build: irida
    image: dfornika/irida
    environment:
      - GET_HOSTS_FROM=dns
    command:
      ["catalina.sh", "run"]
    ports:
      - "8080:8080"
    labels:
      kompose.service.type: Nodeport
    depends_on:
      - irida-db
