version: '3'

services:
  galaxy:
    build: galaxy/.
  db:
    build: db/.
    image: irida-db
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    volumes:
      - mariadb_data:/var/lib/mysql
  irida:
    build: irida/.
    command:
      ["wait-for-it.sh", "db:3306", "--", "catalina.sh", "run"]
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  mariadb_data:
